// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMPuuUrHoUPvhF1PP83bKfCqsm618ub3U',
    appId: '1:881408691575:web:6d6564350f159b1a572572',
    messagingSenderId: '881408691575',
    projectId: 'inventoryhrknives',
    authDomain: 'inventoryhrknives.firebaseapp.com',
    storageBucket: 'inventoryhrknives.firebasestorage.app',
    measurementId: 'G-F72PQQ80R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPuuUrHoUPvhF1PP83bKfCqsm618ub3U',
    appId: '1:881408691575:android:6d6564350f159b1a572572',
    messagingSenderId: '881408691575',
    projectId: 'inventoryhrknives',
    storageBucket: 'inventoryhrknives.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMPuuUrHoUPvhF1PP83bKfCqsm618ub3U',
    appId: '1:881408691575:ios:6d6564350f159b1a572572',
    messagingSenderId: '881408691575',
    projectId: 'inventoryhrknives',
    storageBucket: 'inventoryhrknives.firebasestorage.app',
    iosClientId: '1:881408691575:ios:6d6564350f159b1a572572',
    iosBundleId: 'com.example.inventorydesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMPuuUrHoUPvhF1PP83bKfCqsm618ub3U',
    appId: '1:881408691575:macos:6d6564350f159b1a572572',
    messagingSenderId: '881408691575',
    projectId: 'inventoryhrknives',
    storageBucket: 'inventoryhrknives.firebasestorage.app',
    iosClientId: '1:881408691575:macos:6d6564350f159b1a572572',
    iosBundleId: 'com.example.inventorydesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMPuuUrHoUPvhF1PP83bKfCqsm618ub3U',
    appId: '1:881408691575:windows:6d6564350f159b1a572572',
    messagingSenderId: '881408691575',
    projectId: 'inventoryhrknives',
    storageBucket: 'inventoryhrknives.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDMPuuUrHoUPvhF1PP83bKfCqsm618ub3U',
    appId: '1:881408691575:linux:6d6564350f159b1a572572',
    messagingSenderId: '881408691575',
    projectId: 'inventoryhrknives',
    storageBucket: 'inventoryhrknives.firebasestorage.app',
  );
}
